version: 2.1
orbs:
  heroku: circleci/heroku@0.0.6

workflows:
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

jobs:
  # 1. Build
  build:
    # 1.1 Docker Images to be the background of this setup
    docker:
      - image: circleci/ruby:2.7.1-browsers
        environment:
          RAILS_ENV: test
          DATABASE_URL: "postgres://test_user:test_password@localhost:5432/test_stoic_db"
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_stoic_db
  # 1.2 Run commands to install relevant packages
    steps:
      - checkout
      - run: echo "Henry here we go. Building Stoic Penknife for you. If all you had was this echo command CircleCI would consider the build a green success. A friendly salutation from the CircleCI Build."
      - run: gem install bundler:2.0.1
      - run: bundle install
      # Javascript Runtime needed, see https://github.com/rails/execjs. That's why I install NodeJS below. The extra nodesource.com line is because
      # There is an error due to the version of Node combined with the Ruby Docker image. See: https://github.com/ai/autoprefixer-rails/issues/144
      - run: curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
      - run: sudo apt-get install -y nodejs
  # 1.3  Set Up Database
      - run: bin/rails db:create
      - run: bin/rails db:migrate
  # 2. Test
  # A way to dump shell environment variables to the screen
  # - run: env
      - run: bundle exec rubocop
      - run: bundle exec rspec
        # when: always - This is a change that is not yet implemented to the Code Cov "Orb"
  # 3. Deploy to Heroku
    # Note API Token - generate by heroku auth:token - https://stackoverflow.com/questions/27810419/git-push-heroku-master-is-still-asking-for-authentication. Will expire in 2020.
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          only-branch: master

